### ISSUE TITLE
Problem with example-sdk.php

### ISSUE THREAD

**Issue by herkenham** [wellnessliving/wl-sdk#139]
When running example code I got the following error:

herkenham@stringsattachedbungeefitness:~/WellnessLiving/wl-sdk$ php example-sdk.php
PHP Fatal error:  Uncaught Error: Call to undefined function WellnessLiving\bcdiv() in /home/herkenham/WellnessLiving/wl-sdk/WellnessLiving/WlTool.php:38
Stack trace:
#0 /home/herkenham/WellnessLiving/wl-sdk/WellnessLiving/WlModelAbstract.php(393): WellnessLiving\WlTool::dateMysqlHttp()
#1 /home/herkenham/WellnessLiving/wl-sdk/WellnessLiving/WlModelAbstract.php(359): WellnessLiving\WlModelAbstract->requestPrepare()
#2 /home/herkenham/WellnessLiving/wl-sdk/WellnessLiving/WlModelAbstract.php(273): WellnessLiving\WlModelAbstract->request()
#3 /home/herkenham/WellnessLiving/wl-sdk/example-sdk.php(23): WellnessLiving\WlModelAbstract->get()
#4 {main}
  thrown in /home/herkenham/WellnessLiving/wl-sdk/WellnessLiving/WlTool.php on line 38

**Comment by herkenham** [comment]
I solved this issue (and the next issue) by executing the following two commands:

sudo apt install php-bcmath
sudo apt install php-curl

After that, the example executed properly.
